#!/usr/bin/env ruby

require 'imor'

ARGV.each do |file_name|
  if File.directory?(file_name)
    files = Dir["#{file_name}/**/*"].reject {|fn| File.directory?(fn) }
    files.each { |f| Imor::Scanner.new(f).() }
  else
    Imor::Scanner.new(file_name).()
  end
end

